### ISSUE TITLE
HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by ggdhines-zz** [zooniverse/aggregation#105]
View details in Rollbar: [https://rollbar.com/Zooniverse/Zooniverse_Aggregation/items/86/](https://rollbar.com/Zooniverse/Zooniverse_Aggregation/items/86/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 568, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 495, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/app/engine/jobs.py", line 11, in aggregate
    project.__setup__()
  File "/app/engine/aggregation_api.py", line 222, in __setup__
    self.__get_project_details__()
  File "/app/engine/aggregation_api.py", line 651, in __get_project_details__
    data = self.__panoptes_call__(request)
  File "/app/engine/aggregation_api.py", line 1202, in __panoptes_call__
    response = urllib2.urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found
```

**Comment by ggdhines-zz** [comment]
haven't seen a repeat of this in a long while so closing
