### ISSUE TITLE
TypeError: __init__() takes exactly 3 arguments (4 given)

### ISSUE THREAD

**Issue by ggdhines-zz** [zooniverse/aggregation#112]
View details in Rollbar: [https://rollbar.com/Zooniverse/Zooniverse_Aggregation/items/92/](https://rollbar.com/Zooniverse/Zooniverse_Aggregation/items/92/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 568, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 495, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/app/engine/jobs.py", line 12, in aggregate
    project.__aggregate__()
  File "/app/engine/aggregation_api.py", line 319, in __aggregate__
    aggregations = self.__cluster__(used_shapes,raw_markings,image_dimensions)
  File "/app/engine/aggregation_api.py", line 515, in __cluster__
    algorithm = self.default_clustering_algs[shape](shape,self,{})
TypeError: __init__() takes exactly 3 arguments (4 given)
```

**Comment by ggdhines-zz** [comment]
forgot to mention closed by f1375b4953488b0b23d48a1cf5b0a48230291c20
