### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by ggdhines-zz** [zooniverse/aggregation#123]
View details in Rollbar: [https://rollbar.com/Zooniverse/Zooniverse_Aggregation/items/103/](https://rollbar.com/Zooniverse/Zooniverse_Aggregation/items/103/)

```
Traceback (most recent call last):
  File "./text_aggregation.py", line 603, in <module>
    project.__summarize__()
  File "./text_aggregation.py", line 508, in __summarize__
    self.__restructure_json__()
  File "./text_aggregation.py", line 297, in __restructure_json__
    if subject_id not in self.classification_alg.to_retire:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by ggdhines-zz** [comment]
caused by me cntrl-c'ing a run (realized that I hadn't set things up properly for that specific run)
