### ISSUE TITLE
ValueError: A LinearRing must have at least 3 coordinate tuples

### ISSUE THREAD

**Issue by ggdhines-zz** [zooniverse/aggregation#140]
View details in Rollbar: [https://rollbar.com/Zooniverse/Zooniverse_Aggregation/items/113/](https://rollbar.com/Zooniverse/Zooniverse_Aggregation/items/113/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 568, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 495, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/app/engine/jobs.py", line 12, in aggregate
    project.__aggregate__()
  File "/app/engine/aggregation_api.py", line 333, in __aggregate__
    aggregations = self.__cluster__(used_shapes,raw_markings,image_dimensions,aggregations)
  File "/app/engine/aggregation_api.py", line 553, in __cluster__
    shape_aggregation = algorithm.__aggregate__(raw_markings,image_dimensions)
  File "/app/engine/clustering.py", line 113, in __aggregate__
    'cluster_results,time_to_cluster = self.__cluste...arkings,image_dimensions[subject_id],subject_id)'
  File "/app/engine/blob_clustering.py", line 411, in __cluster__
    poly = Polygon(polygon_pts)
  File "/usr/lib/python2.7/dist-packages/shapely/geometry/polygon.py", line 229, in __init__
    self._geom, self._ndim = geos_polygon_from_py(shell, holes)
  File "/usr/lib/python2.7/dist-packages/shapely/geometry/polygon.py", line 445, in geos_polygon_from_py
    geos_shell, ndim = geos_linearring_from_py(shell)
  File "/usr/lib/python2.7/dist-packages/shapely/geometry/polygon.py", line 393, in geos_linearring_from_py
    "A LinearRing must have at least 3 coordinate tuples")
ValueError: A LinearRing must have at least 3 coordinate tuples
```

**Comment by ggdhines-zz** [comment]
new blob aggregation code no longer uses shapely so not a problem
