### ISSUE TITLE
Key Error during aggregation

### ISSUE THREAD

**Issue by edpaget** [zooniverse/aggregation#15]
After working around #14 I found a further error that I'm unsure of how to resolve:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 558, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 495, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/app/engine/jobs.py", line 9, in aggregate
    tarpath = project.__csv_output__(compress=True)
  File "/app/engine/aggregation_api.py", line 474, in __csv_output__
    for aggregation_dict in self.__get_aggregations__(workflow_id):
  File "/app/engine/aggregation_api.py", line 655, in __get_aggregations__
    aggregation_dict["number_of_users_per_subject"] = cluster["existence"][1]
KeyError: 'existence'
```

**Comment by ggdhines-zz** [comment]
Hey - @edpaget , which project were you trying this on?

**Comment by edpaget** [comment]
I was trying it on Edwardo's Sad Project on staging.
