### ISSUE TITLE
NoHostAvailable: ('Unable to connect to any servers', {'54.152.244.120': error(None, "Tried connecting to [('54.152.244.120', 9042)]. Last error: timed out")})

### ISSUE THREAD

**Issue by ggdhines-zz** [zooniverse/aggregation#150]
View details in Rollbar: [https://rollbar.com/Zooniverse/Zooniverse_Aggregation/items/116/](https://rollbar.com/Zooniverse/Zooniverse_Aggregation/items/116/)

```
Traceback (most recent call last):
  File "/app/engine/text_aggregation.py", line 443, in <module>
    project.__setup__()
  File "/app/engine/text_aggregation.py", line 170, in __setup__
    AggregationAPI.__setup__(self)
  File "/app/engine/aggregation_api.py", line 207, in __setup__
    self.cassandra_session = self.__cassandra_connect__(environment_details["cassandra"])
  File "/app/engine/aggregation_api.py", line 466, in __cassandra_connect__
    raise err
NoHostAvailable: ('Unable to connect to any servers', {'54.152.244.120': error(None, "Tried connecting to [('54.152.244.120', 9042)]. Last error: timed out")})
```

**Comment by ggdhines-zz** [comment]
hopefully just a one off problem connecting to cassandra. will close for now and see if it reappears
