### ISSUE TITLE
Backup Upload to Dropbox failing

### ISSUE THREAD

**Issue by umaepoch** [zooniverse/aggregation#214]
Hi,

Since past 2 months, the backups are not going to the dropbox. The error being received is:

Backup Upload Failed

Oops, your automated backup to Dropbox failed.

Error message:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 124, in take_backup_to_dropbox
    did_not_upload, error_log = backup_to_dropbox()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 165, in backup_to_dropbox
    dropbox_client = upload_file_to_dropbox(filename, "/database", dropbox_client)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 211, in upload_file_to_dropbox
    uploader.upload_chunked()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/dropbox/client.py", line 1182, in upload_chunked
    BytesIO(self.last_block), next_chunk_size, self.offset, self.upload_id)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/dropbox/client.py", line 259, in upload_chunk
    reply = self.rest_client.PUT(url, file_obj, headers)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/dropbox/rest.py", line 327, in PUT
    return cls.IMPL.PUT(*n, **kw)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/dropbox/rest.py", line 264, in PUT
    return self.request("PUT", url, body=body, headers=headers, raw_response=raw_response)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/dropbox/rest.py", line 226, in request
    preload_content=False
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 379, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/rq/timeouts.py", line 51, in handle_death_penalty
    'value ({0} seconds)'.format(self._timeout))
JobTimeoutException: Job exceeded maximum timeout value (300 seconds)

The size of the database is around 1GB. And, I have also tried to increase the timeout in common_site_config.json, by adding this line:

"scheduler_interval": 6000,
But, its still giving this timeout issue. Can anyone please help?
Thanks

**Comment by adammcmaster** [comment]
It doesn't look like you're using our code. Did you mean to open this with [Frappe](https://github.com/frappe/frappe)?
