### ISSUE TITLE
TypeError: request() got an unexpected keyword argument 'json'

### ISSUE THREAD

**Issue by ggdhines-zz** [zooniverse/aggregation#28]
View details in Rollbar: [https://rollbar.com/Zooniverse/Zooniverse_Aggregation/items/13/](https://rollbar.com/Zooniverse/Zooniverse_Aggregation/items/13/)

```
Traceback (most recent call last):
  File "/app/engine/transcription.py", line 954, in __task_aggregation__
    r = requests.post("https://panoptes.zooniverse.org/api/workflows/"+str(self.workflow_id)+"/links/retired_subjects",headers=headers,json=params)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
TypeError: request() got an unexpected keyword argument 'json'
```

**Comment by ggdhines-zz** [comment]
duplicate of #27 - hopefully the code will keep on running at least in this case
