### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by ggdhines-zz** [zooniverse/aggregation#62]
View details in Rollbar: [https://rollbar.com/Zooniverse/Zooniverse_Aggregation/items/50/](https://rollbar.com/Zooniverse/Zooniverse_Aggregation/items/50/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 568, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 495, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/app/engine/jobs.py", line 12, in aggregate
    project.__aggregate__()
  File "/app/engine/aggregation_api.py", line 416, in __aggregate__
    raw_classifications,raw_markings,image_dimensions = self.__sort_annotations__(workflow_id,subject_set,expert)
  File "/app/engine/aggregation_api.py", line 1652, in __sort_annotations__
    for subject_id,user_id,annotation,dimensions in annotation_generator(workflow_id,subject_set):
  File "/app/engine/aggregation_api.py", line 516, in annotation_generator
    for dimensions in metadata["subject_dimensions"]:
TypeError: string indices must be integers
```

**Comment by ggdhines-zz** [comment]
not sure what caused this but the updated version seems to have already fixed it (just need to up load new version shortly)
