### ISSUE TITLE
KeyError: 'task'

### ISSUE THREAD

**Issue by ggdhines-zz** [zooniverse/aggregation#82]
View details in Rollbar: [https://rollbar.com/Zooniverse/Zooniverse_Aggregation/items/65/](https://rollbar.com/Zooniverse/Zooniverse_Aggregation/items/65/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 568, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 495, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/app/engine/jobs.py", line 12, in aggregate
    project.__aggregate__()
  File "/app/engine/aggregation_api.py", line 456, in __aggregate__
    'raw_classifications,raw_markings,image_dimensio...rt_annotations__(workflow_id,subject_set,expert)'
  File "/app/engine/aggregation_api.py", line 1689, in __sort_annotations__
    task_id = task["task"]
KeyError: 'task'
```

**Comment by ggdhines-zz** [comment]
This is from someone (probably Phil) trying to run aggregation on old weather (Perry's version) - this project breaks the annotation model used in the rest of panoptes - specifically there is no "task" key. Spoke to Chris L. about this and he said that Phil is fine with just the raw aggregations so I'm closing this issue for now.
