### ISSUE TITLE
ProgrammingError: column "subject_ids" does not exist
LINE 1: ...ompleted,gold_standard,expert_classifier,metadata,subject_id...
                                                             ^


### ISSUE THREAD

**Issue by ggdhines-zz** [zooniverse/aggregation#86]
View details in Rollbar: [https://rollbar.com/Zooniverse/Zooniverse_Aggregation/items/69/](https://rollbar.com/Zooniverse/Zooniverse_Aggregation/items/69/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 568, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 495, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/app/engine/jobs.py", line 12, in aggregate
    project.__migrate__()
  File "/app/engine/aggregation_api.py", line 1105, in __migrate__
    cur.execute(select)
ProgrammingError: column "subject_ids" does not exist
LINE 1: ...ompleted,gold_standard,expert_classifier,metadata,subject_id...
                                                             ^

```

**Comment by ggdhines-zz** [comment]
closed by
