### ISSUE TITLE
KeyError: u'point clusters'

### ISSUE THREAD

**Issue by ggdhines-zz** [zooniverse/aggregation#91]
View details in Rollbar: [https://rollbar.com/Zooniverse/Zooniverse_Aggregation/items/71/](https://rollbar.com/Zooniverse/Zooniverse_Aggregation/items/71/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 568, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 495, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/app/engine/jobs.py", line 16, in aggregate
    tarpath = writer.__write_out__(compress=True)
  File "/app/engine/csv_output.py", line 443, in __write_out__
    self.__subject_output__(workflow_id,subject_id,aggregations)
  File "/app/engine/csv_output.py", line 281, in __subject_output__
    self.__marking_row__(workflow_id,task_id,subject_id,aggregations[task_id],shape)
  File "/app/engine/csv_output.py", line 492, in __marking_row__
    for cluster_index,cluster in aggregations[shape + " clusters"].items():
KeyError: u'point clusters'
```

**Comment by ggdhines-zz** [comment]
caused by serengeti wildebeest watch (project id 121) - no longer happening
