### ISSUE TITLE
ServerError: <ErrorMessage code=0000 [Server error] message="java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Tried to hard link to file that does not exist /var/lib/cassandra/data/zooniverse/classifications

### ISSUE THREAD

**Issue by ggdhines-zz** [zooniverse/aggregation#95]
View details in Rollbar: [https://rollbar.com/Zooniverse/Zooniverse_Aggregation/items/75/](https://rollbar.com/Zooniverse/Zooniverse_Aggregation/items/75/)

```
Traceback (most recent call last):
  File "./aggregation_api.py", line 1903, in <module>
    project.__migrate__()
  File "./aggregation_api.py", line 1036, in __migrate__
    self.cassandra_session.execute("drop table classifications")
  File "/usr/local/lib/python2.7/dist-packages/cassandra/cluster.py", line 1341, in execute
    result = future.result(timeout)
  File "/usr/local/lib/python2.7/dist-packages/cassandra/cluster.py", line 2865, in result
    raise self._final_exception
ServerError: <ErrorMessage code=0000 [Server error] message="java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Tried to hard link to file that does not exist /var/lib/cassandra/data/zooniverse/classifications/zooniverse-classifications-jb-116-TOC.txt">
```

**Comment by ggdhines-zz** [comment]
doesn't seem to have reoccurred
