### ISSUE TITLE
TransactionRollbackError: canceling statement due to conflict with recovery
DETAIL:  User query might have needed to see row versions that must be removed.


### ISSUE THREAD

**Issue by ggdhines-zz** [zooniverse/aggregation#96]
View details in Rollbar: [https://rollbar.com/Zooniverse/Zooniverse_Aggregation/items/76/](https://rollbar.com/Zooniverse/Zooniverse_Aggregation/items/76/)

```
Traceback (most recent call last):
  File "./aggregation_api.py", line 1903, in <module>
    project.__migrate__()
  File "./aggregation_api.py", line 1072, in __migrate__
    cur.execute(select)
TransactionRollbackError: canceling statement due to conflict with recovery
DETAIL:  User query might have needed to see row versions that must be removed.

```

**Comment by ggdhines-zz** [comment]
doesn't seem to have reoccurred
